### ISSUE TITLE
BUG-Missing link on step 2

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-getting-started#42]
This page:
https://docs.taipy.io/en/latest/getting_started/getting-started-gui/step_02/ReadMe/

Has a non-functional link here:
![image](https://github.com/Avaiga/taipy-getting-started/assets/62465003/edcbdd20-ebe6-4ce3-b2aa-6e0a3b72140b)

**Comment by jrobinAV** [comment]
Done when moving the getting started to tutorials.
